# Generated by Django 5.0.7 on 2024-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=10)),
                ('Contact', models.IntegerField()),
                ('Score', models.FloatField()),
                ('Course', models.CharField(max_length=40)),
            ],
        ),
    ]
